name: CodeTracker Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OAuthToken: ${{ secrets.OAUTHTOKEN }}
      releaseVersion: CI-CodeTracker-SNAPSHOT

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project with Gradle
        run: ./gradlew publishToMavenLocal -x test -x javadoc -PbuildVersion=${{ env.releaseVersion }}

      - name: Clone CodeTracker and Run the tests
        run: |
          git clone https://github.com/jodavimehran/code-tracker &&
          cd code-tracker &&
          mvn -B package --file pom.xml -Drm.version=${{ env.releaseVersion }}
